export const ROUTES = {
  HOME_ROUTER: "/home",
  CUSTOMER_LOGIN_ROUTER: "/customer/login",
  CUSTOMER_REGISTER_ROUTER: "/customer/register",
  CUSTOMER_PROFILE_ROUTER: "/customer/profile",
  CUSTOMER_MAINSCREEN_ROUTER: "/customer/mainscreen",
  CUSTOMER_CONTRACT_HISTORY: "/customer/contract/history",
  CUSTOMER_CONTRACT_DETAILS: "/customer/contract/:id",
  CUSTOMER_CONTRACT_REQUEST: "/customer/contract/request",
  CUSTOMER_RESET_PASSWORD_ROUTER: "/customer/password/reset",
  STAFF_MAINSCREEN_ROUTER: "/staff/staffscreen",
  STAFF_CONTRACT_ROUTER: "/staff/contract",
  STAFF_COMPENSATION_ROUTER: "/staff/compensation",
  STAFF_CUSTOMER_ROUTER: "/staff/customer",
  MANAGER_SCREEN_ROUTER: "/manager",
  MANAGER_CONTRACT_ROUTER: "/manager/contract",
  MANAGER_COMPENSATION_ROUTER: "/manager/compensation",
  MANAGER_CONTRACTYPE_ROUTER: "/manager/contractype",
  MANAGER_ACCOUNT_ROUTER: "/manager/account",
};
