export const ROUTES = {
  HOME: "/home",
  CONTRACT_TYPE: "/contract/type/:id",
  CUSTOMER_LOGIN: "/customer/login",
  CUSTOMER_REGISTER: "/customer/register",
  CUSTOMER_VERIFY: "/customer/verify",
  CUSTOMER_PROFILE: "/customer/profile",
  CUSTOMER_CONTRACT_HISTORY: "/customer/contract",
  CUSTOMER_CONTRACT_DETAILS: "/customer/contract/:id",
  CUSTOMER_CONTRACT_REQUEST: "/customer/contract/request",
  CUSTOMER_COMPENSATION_LIST: "/customer/compensation",
  CUSTOMER_COMPENSATION_DETAILS: "/customer/compensation/:id",
  CUSTOMER_COMPENSATION_REQUEST: "/customer/compensation/request",
  CUSTOMER_CHANGE_PASSWORD: "/customer/password/change",
  CUSTOMER_RESET_PASSWORD: "/customer/password/reset",
  CUSTOMER_FORGET_PASSWORD: "/customer/password/forget",
  STAFF_CONTRACT: "/staff/contract",
  STAFF_CONTRACT_DETAILS: "/staff/contract/:id",
  STAFF_COMPENSATION: "/staff/compensation",
  STAFF_COMPENSATION_DETAILS: "/staff/compensation/:id",
  STAFF_CUSTOMER: "/staff/customer",
  MANAGER_LOGIN: "/manager/login",
  MANAGER_CONTRACT: "/manager/contract",
  MANAGER_CONTRACT_DETAILS: "/manager/contract/:id",
  MANAGER_COMPENSATION: "/manager/compensation",
  MANAGER_COMPENSATION_DETAILS: "/manager/compensation/:id",
  MANAGER_CONTRACTYPE: "/manager/contract/type",
  MANAGER_CONTRACTYPE_DETAILS: "/manager/contract/type/:id",
  MANAGER_INSERT_CONTRACTYPE: "/manager/contract/type/add",
  MANAGER_CUSTOMER: "/manager/customer",
  MANAGER_EMPLOYEE: "/manager/employee",
  MANAGER_EMPLOYEE_DETAILS: "/manager/employee/:id",
  ERROR: {
    404: "/404",
  },
};
